### ISSUE TITLE
Provide functionality to "My Posts" screen

### ISSUE THREAD

**Issue by MikeWarren2014** [MikeWarren2014/171106-Project2-SHOULDi#20]
implement logic to `posts.my.component.ts`

**Comment by Sintrias** [comment]
Started. Sending get request to back-end. Back-end needs implementation for sending response. Front-end will need to store posts. Functionality for displaying them should be good.

**Comment by MikeWarren2014** [comment]
Copied structure,TypeScript,CSS from feed component into that component today. This should theoretically work.

**Comment by MikeWarren2014** [comment]
added "flag comments" feature

**Comment by MikeWarren2014** [comment]
component has full functionality.
